import { subDays } from 'date-fns';
import type { PinsData } from '@/lib/store';

export const DEFAULT_DATA: PinsData = {
  logs: [
    {
      id: crypto.randomUUID(),
      siteId: 'mid-left-abdomen',
      compound: 'BPC-157',
      dose: 250,
      unit: 'mcg',
      timestamp: new Date().toISOString(),
      notes: 'Morning dose',
      updatedAt: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      siteId: 'right-deltoid',
      compound: 'TB-500',
      dose: 2.5,
      unit: 'mg',
      timestamp: subDays(new Date(), 1).toISOString(),
      updatedAt: subDays(new Date(), 1).toISOString(),
    },
    {
      id: crypto.randomUUID(),
      siteId: 'left-glute',
      compound: 'Semaglutide',
      dose: 0.25,
      unit: 'mg',
      timestamp: subDays(new Date(), 3).toISOString(),
      updatedAt: subDays(new Date(), 3).toISOString(),
    },
    {
      id: crypto.randomUUID(),
      siteId: 'mid-right-abdomen',
      compound: 'BPC-157',
      dose: 250,
      unit: 'mcg',
      timestamp: subDays(new Date(), 4).toISOString(),
      updatedAt: subDays(new Date(), 4).toISOString(),
    },
    {
      id: crypto.randomUUID(),
      siteId: 'left-deltoid',
      compound: 'TB-500',
      dose: 2.5,
      unit: 'mg',
      timestamp: subDays(new Date(), 5).toISOString(),
      updatedAt: subDays(new Date(), 5).toISOString(),
    },
  ],
  inventory: [
    {
      id: crypto.randomUUID(),
      name: 'BPC-157',
      concentration: 5000,
      totalVolume: 2,
      remainingVolume: 1.2,
      unit: 'mcg',
      color: '#3b82f6',
      frequency: 'Daily',
      defaultDose: 250,
      updatedAt: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: 'TB-500',
      concentration: 5,
      totalVolume: 2,
      remainingVolume: 0.8,
      unit: 'mg',
      color: '#10b981',
      frequency: '2x/week',
      defaultDose: 2.5,
      updatedAt: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: 'Semaglutide',
      concentration: 2.5,
      totalVolume: 1,
      remainingVolume: 0.75,
      unit: 'mg',
      color: '#f59e0b',
      frequency: 'Weekly',
      defaultDose: 0.25,
      updatedAt: new Date().toISOString(),
    },
  ],
  schedule: [
    {
      id: crypto.randomUUID(),
      compound: 'BPC-157',
      dose: 250,
      unit: 'mcg',
      time: '08:00',
      days: [0, 1, 2, 3, 4, 5, 6],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      compound: 'TB-500',
      dose: 2.5,
      unit: 'mg',
      time: '20:00',
      days: [1, 4],
      active: true,
      updatedAt: new Date().toISOString(),
    },
  ],
};